# Generated by Django 4.1.7 on 2023-04-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_type',
            field=models.CharField(choices=[(1, 'Admin'), (2, 'Organization Admin'), (3, 'Patients'), (4, 'Doctors')], default=1, max_length=10),
        ),
    ]
