# Generated by Django 4.1.7 on 2023-04-09 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_alter_users_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Organization Admin', 'Organization Admin'), ('Patients', 'Patients'), ('Doctors', 'Doctors')], default='Admin', max_length=25),
        ),
    ]
